INSERT INTO deck (deck_name, member_only, category, jlpt_level, language_id, active, created_at, updated_at) VALUES
-- N5 Kanji Decks
('JLPT N5 Kanji Deck 1 (Kanji 1 to 20)', false, 'KANJI', 5, 'JP', true, NOW(), NOW()),
('JLPT N5 Kanji Deck 2 (Kanji 21 to 40)', false, 'KANJI', 5, 'JP', true, NOW(), NOW()),
('JLPT N5 Kanji Deck 3 (Kanji 41 to 60)', false, 'KANJI', 5, 'JP', true, NOW(), NOW()),
('JLPT N5 Kanji Deck 4 (Kanji 61 to 80)', false, 'KANJI', 5, 'JP', true, NOW(), NOW()),
('JLPT N5 Kanji Deck 5 (Kanji 81 to 103)', false, 'KANJI', 5, 'JP', true, NOW(), NOW()),
-- N5 Vocab Decks
('JLPT N5 Vocabulary Deck 1 (Vocabulary 1 to 100)', false, 'VOCABULARY', 5, 'JP', true, NOW(), NOW()),
('JLPT N5 Vocabulary Deck 2 (Vocabulary 101 to 200)', false, 'VOCABULARY', 5, 'JP', true, NOW(), NOW()),
('JLPT N5 Vocabulary Deck 3 (Vocabulary 201 to 300)', false, 'VOCABULARY', 5, 'JP', true, NOW(), NOW()),
('JLPT N5 Vocabulary Deck 4 (Vocabulary 301 to 400)', false, 'VOCABULARY', 5, 'JP', true, NOW(), NOW()),
('JLPT N5 Vocabulary Deck 5 (Vocabulary 401 to 500)', false, 'VOCABULARY', 5, 'JP', true, NOW(), NOW()),
('JLPT N5 Vocabulary Deck 6 (Vocabulary 501 to 600)', false, 'VOCABULARY', 5, 'JP', true, NOW(), NOW()),
('JLPT N5 Vocabulary Deck 7 (Vocabulary 601 to 700)', false, 'VOCABULARY', 5, 'JP', true, NOW(), NOW()),
('JLPT N5 Vocabulary Deck 8 (Vocabulary 701 to 800)', false, 'VOCABULARY', 5, 'JP', true, NOW(), NOW()),
-- N5 Kana Decks
('JLPT N5 Hiragana Deck', false, 'KANA', 5, 'JP', true, NOW(), NOW()),
('JLPT N5 Katakana Deck', false, 'KANA', 5, 'JP', true, NOW(), NOW()),
-- N5 Grammar decks
('JLPT N5 Grammar Deck 1, grammar rules 1 to 20', false, 'GRAMMAR', 5, 'JP', true, NOW(), NOW()),
('JLPT N5 Grammar Deck 2, grammar rules 21 to 40', false, 'GRAMMAR', 5, 'JP', true, NOW(), NOW()),
('JLPT N5 Grammar Deck 3, grammar rules 41 to 60', false, 'GRAMMAR', 5, 'JP', true, NOW(), NOW()),
('JLPT N5 Grammar Deck 4, grammar rules 61 to 80', false, 'GRAMMAR', 5, 'JP', true, NOW(), NOW()),
-- N4 Kanji Decks
('JLPT N4 Kanji Deck 1 (Kanji 1 to 20)', false, 'KANJI', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Kanji Deck 2 (Kanji 21 to 40)', false, 'KANJI', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Kanji Deck 3 (Kanji 41 to 60)', true, 'KANJI', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Kanji Deck 4 (Kanji 61 to 80)', true, 'KANJI', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Kanji Deck 5 (Kanji 81 to 100)', true, 'KANJI', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Kanji Deck 6 (Kanji 101 to 120)', true, 'KANJI', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Kanji Deck 7 (Kanji 121 to 140)', true, 'KANJI', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Kanji Deck 8 (Kanji 141 to 160)', true, 'KANJI', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Kanji Deck 9 (Kanji 161 to 180)', true, 'KANJI', 4, 'JP', true, NOW(), NOW()),
-- N4 Vocab Decks
('JLPT N4 Vocabulary Deck 1 (Vocabulary 1 to 100)', false, 'VOCABULARY', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Vocabulary Deck 2 (Vocabulary 101 to 200)', false, 'VOCABULARY', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Vocabulary Deck 3 (Vocabulary 201 to 300)', true, 'VOCABULARY', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Vocabulary Deck 4 (Vocabulary 301 to 400)', true, 'VOCABULARY', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Vocabulary Deck 5 (Vocabulary 401 to 500)', true, 'VOCABULARY', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Vocabulary Deck 6 (Vocabulary 501 to 600)', true, 'VOCABULARY', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Vocabulary Deck 7 (Vocabulary 601 to 700)', true, 'VOCABULARY', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Vocabulary Deck 8 (Vocabulary 701 to 800)', true, 'VOCABULARY', 4, 'JP', true, NOW(), NOW()),
-- N4 Grammar decks
('JLPT N4 Grammar Deck 1, grammar rules 1 to 20', false, 'GRAMMAR', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Grammar Deck 2, grammar rules 21 to 40', false, 'GRAMMAR', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Grammar Deck 3, grammar rules 41 to 60', true, 'GRAMMAR', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Grammar Deck 4, grammar rules 61 to 80', true, 'GRAMMAR', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Grammar Deck 5, grammar rules 81 to 100', true, 'GRAMMAR', 4, 'JP', true, NOW(), NOW()),
('JLPT N4 Grammar Deck 6, grammar rules 101 to 120', true, 'GRAMMAR', 4, 'JP', true, NOW(), NOW()),
-- N3 Kanji Decks
('JLPT N3 Kanji Deck 1 (Kanji 1 to 20)', false, 'KANJI', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Kanji Deck 2 (Kanji 21 to 40)', false, 'KANJI', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Kanji Deck 3 (Kanji 41 to 60)', true, 'KANJI', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Kanji Deck 4 (Kanji 61 to 80)', true, 'KANJI', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Kanji Deck 5 (Kanji 81 to 100)', true, 'KANJI', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Kanji Deck 6 (Kanji 101 to 120)', true, 'KANJI', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Kanji Deck 7 (Kanji 121 to 140)', true, 'KANJI', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Kanji Deck 8 (Kanji 141 to 160)', true, 'KANJI', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Kanji Deck 9 (Kanji 161 to 180)', true, 'KANJI', 3, 'JP', true, NOW(), NOW()),
-- N3 Vocab Decks
('JLPT N3 Vocabulary Deck 1 (Vocabulary 1 to 100)', false, 'VOCABULARY', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Vocabulary Deck 2 (Vocabulary 101 to 200)', false, 'VOCABULARY', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Vocabulary Deck 3 (Vocabulary 201 to 300)', true, 'VOCABULARY', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Vocabulary Deck 4 (Vocabulary 301 to 400)', true, 'VOCABULARY', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Vocabulary Deck 5 (Vocabulary 401 to 500)', true, 'VOCABULARY', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Vocabulary Deck 6 (Vocabulary 501 to 600)', true, 'VOCABULARY', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Vocabulary Deck 7 (Vocabulary 601 to 700)', true, 'VOCABULARY', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Vocabulary Deck 8 (Vocabulary 701 to 800)', true, 'VOCABULARY', 3, 'JP', true, NOW(), NOW()),
-- N3 Grammar decks
('JLPT N3 Grammar Deck 1, grammar rules 1 to 20', false, 'GRAMMAR', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Grammar Deck 2, grammar rules 21 to 40', false, 'GRAMMAR', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Grammar Deck 3, grammar rules 41 to 60', true, 'GRAMMAR', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Grammar Deck 4, grammar rules 61 to 80', true, 'GRAMMAR', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Grammar Deck 5, grammar rules 81 to 100', true, 'GRAMMAR', 3, 'JP', true, NOW(), NOW()),
('JLPT N3 Grammar Deck 6, grammar rules 101 to 120', true, 'GRAMMAR', 3, 'JP', true, NOW(), NOW()),
-- N2 Kanji Decks
('JLPT N2 Kanji Deck 1 (Kanji 1 to 20)', false, 'KANJI', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Kanji Deck 2 (Kanji 21 to 40)', false, 'KANJI', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Kanji Deck 3 (Kanji 41 to 60)', true, 'KANJI', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Kanji Deck 4 (Kanji 61 to 80)', true, 'KANJI', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Kanji Deck 5 (Kanji 81 to 100)', true, 'KANJI', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Kanji Deck 6 (Kanji 101 to 120)', true, 'KANJI', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Kanji Deck 7 (Kanji 121 to 140)', true, 'KANJI', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Kanji Deck 8 (Kanji 141 to 160)', true, 'KANJI', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Kanji Deck 9 (Kanji 161 to 180)', true, 'KANJI', 2, 'JP', true, NOW(), NOW()),
-- N2 Vocab Decks
('JLPT N2 Vocabulary Deck 1 (Vocabulary 1 to 100)', false, 'VOCABULARY', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Vocabulary Deck 2 (Vocabulary 101 to 200)', false, 'VOCABULARY', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Vocabulary Deck 3 (Vocabulary 201 to 300)', true, 'VOCABULARY', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Vocabulary Deck 4 (Vocabulary 301 to 400)', true, 'VOCABULARY', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Vocabulary Deck 5 (Vocabulary 401 to 500)', true, 'VOCABULARY', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Vocabulary Deck 6 (Vocabulary 501 to 600)', true, 'VOCABULARY', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Vocabulary Deck 7 (Vocabulary 601 to 700)', true, 'VOCABULARY', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Vocabulary Deck 8 (Vocabulary 701 to 800)', true, 'VOCABULARY', 2, 'JP', true, NOW(), NOW()),
-- N2 Grammar decks
('JLPT N2 Grammar Deck 1, grammar rules 1 to 20', false, 'GRAMMAR', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Grammar Deck 2, grammar rules 21 to 40', false, 'GRAMMAR', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Grammar Deck 3, grammar rules 41 to 60', true, 'GRAMMAR', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Grammar Deck 4, grammar rules 61 to 80', true, 'GRAMMAR', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Grammar Deck 5, grammar rules 81 to 100', true, 'GRAMMAR', 2, 'JP', true, NOW(), NOW()),
('JLPT N2 Grammar Deck 6, grammar rules 101 to 120', true, 'GRAMMAR', 2, 'JP', true, NOW(), NOW()),
-- N1 Kanji Decks
('JLPT N1 Kanji Deck 1 (Kanji 1 to 20)', false, 'KANJI', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Kanji Deck 2 (Kanji 21 to 40)', false, 'KANJI', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Kanji Deck 3 (Kanji 41 to 60)', true, 'KANJI', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Kanji Deck 4 (Kanji 61 to 80)', true, 'KANJI', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Kanji Deck 5 (Kanji 81 to 100)', true, 'KANJI', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Kanji Deck 6 (Kanji 101 to 120)', true, 'KANJI', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Kanji Deck 7 (Kanji 121 to 140)', true, 'KANJI', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Kanji Deck 8 (Kanji 141 to 160)', true, 'KANJI', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Kanji Deck 9 (Kanji 161 to 180)', true, 'KANJI', 1, 'JP', true, NOW(), NOW()),
-- N1 Vocab Decks
('JLPT N1 Vocabulary Deck 1 (Vocabulary 1 to 100)', false, 'VOCABULARY', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Vocabulary Deck 2 (Vocabulary 101 to 200)', false, 'VOCABULARY', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Vocabulary Deck 3 (Vocabulary 201 to 300)', true, 'VOCABULARY', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Vocabulary Deck 4 (Vocabulary 301 to 400)', true, 'VOCABULARY', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Vocabulary Deck 5 (Vocabulary 401 to 500)', true, 'VOCABULARY', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Vocabulary Deck 6 (Vocabulary 501 to 600)', true, 'VOCABULARY', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Vocabulary Deck 7 (Vocabulary 601 to 700)', true, 'VOCABULARY', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Vocabulary Deck 8 (Vocabulary 701 to 800)', true, 'VOCABULARY', 1, 'JP', true, NOW(), NOW()),
-- N1 Grammar decks
('JLPT N1 Grammar Deck 1, grammar rules 1 to 20', false, 'GRAMMAR', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Grammar Deck 2, grammar rules 21 to 40', false, 'GRAMMAR', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Grammar Deck 3, grammar rules 41 to 60', true, 'GRAMMAR', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Grammar Deck 4, grammar rules 61 to 80', true, 'GRAMMAR', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Grammar Deck 5, grammar rules 81 to 100', true, 'GRAMMAR', 1, 'JP', true, NOW(), NOW()),
('JLPT N1 Grammar Deck 6, grammar rules 101 to 120', true, 'GRAMMAR', 1, 'JP', true, NOW(), NOW());