version: "3.7"

services:
  back-end:
    build:
      context: ./server
      args:
        SERVER_SKIP_CI: ${SERVER_SKIP_CI}
    restart: always
    ports:
    - "3001:3001"
    container_name: backend-server
    environment:
      POSTGRES_HOST: "database"
      POSTGRES_USER: "postgres"
      POSTGRES_DATABASE: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - local

  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - local

  redis:
    image: redis
    ports:
      - 6379:6379

networks:
  local:
    driver: bridge
