const errors = {
  inputValueMissingError: 'inputValueMissingError',
  inputValueTypeError: 'inputValueTypeError',
  passwordMismatchError: 'passwordMismatchError',
  passwordValidationError: 'passwordValidationError',
  requiredPasswordError: 'requiredPasswordError',
  notEmailError: 'notEmailError',
  emailMaxLengthError: 'emailMaxLengthError',
  requiredEmailError: 'requiredEmailError',
  usernameValidationError: 'usernameValidationError',
  emailInUseError: 'emailInUseError',
  usernameInUseError: 'usernameInUseError',
  internalServerError: 'internalServerError',
  userOrPassIncorrectError: 'userOrPassIncorrectError',
  notAuthError: 'notAuthError',
  changePasswordValueMissingError: 'changePasswordValueMissingError',
  currAndNewPassEqualError: 'currAndNewPassEqualError',
  currentPasswordIncorrect: 'currentPasswordIncorrect',
  invalidJlptLevelError: 'invalidJlptLevelError',
  invalidLanguageIdError: 'invalidLanguageIdError',
  invalidResultIdError: 'invalidResultIdError',
  limitReviewsRangeError: 'limitReviewsRangeError',
  noDueCardsError: 'noDueCardsError',
  noNewCardsError: 'noNewCardsError',
  negativeNumberTypeError: 'negativeNumberTypeError',
  nonExistingIdError: 'nonExistingId',
  nonExistingDeckError: 'nonExistingDeck',
  passwordMaxLengthError: 'passwordMaxLengthError',
  passwordMinLengthError: 'passwordMinLengthError',
  requiredPasswordConfirmError: 'requiredPasswordConfirmError',
  passwordNumberError: 'passwordNumberError',
  passwordUppercaseError: 'passwordUppercaseError',
  passwordLowercaseError: 'passwordLowercaseError'
};

module.exports = errors;
