version: "3.7"

services:
  back-end-test:
    build: 
      context: ../server/
      args:
        SERVER_SKIP_CI: ${SERVER_SKIP_CI}
    depends_on:
      - database-test
      - redis-test
    ports:
    - "3001:3001"
    tty: true
    container_name: backend-server-test
    environment:
      POSTGRES_HOST: "database-test"
      POSTGRES_USER: "postgres"
      POSTGRES_DATABASE: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      JWT_SECRET: "test_secret"
      NODE_ENV: "test"
      REDIS_HOST: "redis-test"
      REDIS_PORT: 6379
    networks:
      - local

  database-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - local

  redis-test:
    image: redis
    ports:
      - 6379:6379
    networks:
      - local

networks:
  local:
    driver: bridge
