import {
  AccountErrors, AdminErrors, BugErrors,
  CardErrors, DeckErrors, GeneralErrors,
  ReviewErrors, SessionErrors, ValidationErrors
} from '../types';

export const accountErrors: AccountErrors = {
  ERR_ACCOUNT_NOT_FOUND: 'ERR_ACCOUNT_NOT_FOUND',
  ERR_USERNAME_IN_USE: 'ERR_USERNAME_IN_USE',
  ERR_EMAIL_IN_USE: 'ERR_EMAIL_IN_USE',
  ERR_EMAIL_NOT_FOUND: 'ERR_EMAIL_NOT_FOUND',
  ERR_MEMBER_FEATURE: 'ERR_MEMBER_FEATURE',
  ERR_EMAIL_NOT_CONFIRMED: 'ERR_EMAIL_NOT_CONFIRMED',
  ERR_CONFIRMATION_CODE_NOT_FOUND: 'ERR_CONFIRMATION_CODE_NOT_FOUND',
  ERR_CONFIRMATION_CODE_EXPIRED: 'ERR_CONFIRMATION_CODE_EXPIRED',
  ERR_EMAIL_ALREADY_CONFIRMED: 'ERR_EMAIL_ALREADY_CONFIRMED',
  ERR_INCORRECT_ACTION_TYPE: 'ERR_INCORRECT_ACTION_TYPE',
  ERR_EMAIL_OR_PASSWORD_INCORRECT: 'ERR_EMAIL_OR_PASSWORD_INCORRECT',
  ERR_PASSWORD_CURRENT_AND_NEW_EQUAL: 'ERR_PASSWORD_CURRENT_AND_NEW_EQUAL',
  ERR_PASSWORD_CURRENT_INCORRECT: 'ERR_PASSWORD_CURRENT_INCORRECT',
  ERR_USERNAME_CHANGE_INTERVAL: 'ERR_USERNAME_CHANGE_INTERVAL'
};

export const adminErrors: AdminErrors = {
  ERR_NO_ADMIN_RIGHTS: 'ERR_NO_ADMIN_RIGHTS',
  ERR_NO_ADMIN_READ_RIGHTS: 'ERR_NO_ADMIN_READ_RIGHTS',
  ERR_NO_ADMIN_WRITE_RIGHTS: 'ERR_NO_ADMIN_WRITE_RIGHTS'
};

export const bugErrors: BugErrors = {
  ERR_BUG_BY_ID_NOT_FOUND: 'ERR_BUG_BY_ID_NOT_FOUND',
  ERR_INVALID_BUG_TYPE: 'ERR_INVALID_BUG_TYPE',
  ERR_BUG_TYPE_REQUIRED: 'ERR_BUG_TYPE_REQUIRED',
  ERR_BUG_PAGELIMIT_EXCEEDED: 'ERR_BUG_PAGELIMIT_EXCEEDED',
  ERR_BUG_MESSAGE_TOO_SHORT: 'ERR_BUG_MESSAGE_TOO_SHORT',
  ERR_BUG_MESSAGE_TOO_LONG: 'ERR_BUG_MESSAGE_TOO_LONG',
  ERR_BUG_SOLVE_MESSAGE_TOO_SHORT: 'ERR_BUG_SOLVE_MESSAGE_TOO_SHORT',
  ERR_BUG_SOLVE_MESSAGE_TOO_LONG: 'ERR_BUG_SOLVE_MESSAGE_TOO_LONG'
};

export const cardErrors: CardErrors = {
  ERR_REVIEW_INTERVAL_TOO_LONG: 'ERR_REVIEW_INTERVAL_TOO_LONG',
  ERR_REVIEW_INTERVAL_TOO_SHORT: 'ERR_REVIEW_INTERVAL_TOO_SHORT',
  ERR_NO_DUE_CARDS: 'ERR_NO_DUE_CARDS',
  ERR_STORY_TOO_LONG: 'ERR_STORY_TOO_LONG',
  ERR_STORY_TOO_SHORT: 'ERR_STORY_TOO_SHORT',
  ERR_HINT_TOO_LONG: 'ERR_HINT_TOO_LONG',
  ERR_HINT_TOO_SHORT: 'ERR_HINT_TOO_SHORT',
  ERR_PROVIDE_STORY_OR_HINT: 'ERR_PROVIDE_STORY_OR_HINT',
  ERR_CARD_NOT_FOUND: 'ERR_CARD_NOT_FOUND',
  ERR_INVALID_CARD_TYPE: 'ERR_INVALID_CARD_TYPE'
};

export const deckErrors: DeckErrors = {
  ERR_NO_DECKS_FOUND: 'ERR_NO_DECKS_FOUND',
  ERR_NOT_ACTIVE_DECK: 'ERR_NOT_ACTIVE_DECK',
  ERR_DECK_NOT_FOUND: 'ERR_DECK_NOT_FOUND'
};

export const generalErrors: GeneralErrors = {
  ERR_INVALID_LANGUAGE_ID: 'ERR_INVALID_LANGUAGE_ID',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN'
};

export const reviewErrors: ReviewErrors = {
  ERR_LIMIT_REVIEWS_TOO_HIGH: 'ERR_LIMIT_REVIEWS_TOO_HIGH',
  ERR_LIMIT_REVIEWS_TOO_LOW: 'ERR_LIMIT_REVIEWS_TOO_LOW',
  ERR_NEW_REVIEWS_VALUE_TOO_HIGH: 'ERR_NEW_REVIEWS_VALUE_TOO_HIGH',
  ERR_NEW_REVIEWS_VALUE_TOO_LOW: 'ERR_NEW_REVIEWS_VALUE_TOO_LOW',
  ERR_PUSH_REVIEWS_LIMIT_EXCEEDED: 'ERR_PUSH_REVIEWS_LIMIT_EXCEEDED',
  ERR_INVALID_RESULT_TYPE: 'ERR_INVALID_RESULT_TYPE'
};

export const sessionErrors: SessionErrors = {
  ERR_SESSION_NOT_FOUND: 'ERR_SESSION_NOT_FOUND',
  ERR_SESSION_EXPIRED: 'ERR_SESSION_EXPIRED',
  ERR_NOT_OWNER_OF_SESSION: 'ERR_NOT_OWNER_OF_SESSION',
  ERR_JWT_EXPIRED: 'ERR_JWT_EXPIRED'
};

export const validationErrors: ValidationErrors = {
  ERR_INPUT_VALUE_MISSING: 'ERR_INPUT_VALUE_MISSING',
  ERR_INVALID_DATE: 'ERR_INVALID_DATE',
  ERR_DATE_REQUIRED: 'ERR_DATE_REQUIRED',
  ERR_NOT_VALID_EMAIL: 'ERR_NOT_VALID_EMAIL',
  ERR_PASSWORD_REQUIRED: 'ERR_PASSWORD_REQUIRED',
  ERR_EMAIL_TOO_LONG: 'ERR_EMAIL_TOO_LONG',
  ERR_PASSWORD_MISMATCH: 'ERR_PASSWORD_MISMATCH',
  ERR_INPUT_TYPE: 'ERR_INPUT_TYPE',
  ERR_EMAIL_REQUIRED: 'ERR_EMAIL_REQUIRED',
  ERR_RESULT_TYPE_REQUIRED: 'ERR_RESULT_TYPE_REQUIRED',
  ERR_PASSWORD_NUMBER: 'ERR_PASSWORD_NUMBER',
  ERR_PASSWORD_UPPERCASE: 'ERR_PASSWORD_UPPERCASE',
  ERR_PASSWORD_LOWERCASE: 'ERR_PASSWORD_LOWERCASE',
  ERR_PASSWORD_TOO_LONG: 'ERR_PASSWORD_TOO_LONG',
  ERR_PASSWORD_TOO_SHORT: 'ERR_PASSWORD_TOO_SHORT',
  ERR_ZERO_OR_NEGATIVE_NUMBER: 'ERR_ZERO_OR_NEGATIVE_NUMBER',
  ERR_PASSWORD_CONFIRMATION_REQUIRED: 'ERR_PASSWORD_CONFIRMATION_REQUIRED',
  ERR_USERNAME_TOO_LONG: 'ERR_USERNAME_TOO_LONG',
  ERR_USERNAME_TOO_SHORT: 'ERR_USERNAME_TOO_SHORT',
  ERR_USERNAME_REQUIRED: 'ERR_USERNAME_REQUIRED',
  ERR_TOS_NOT_ACCEPTED: 'ERR_TOS_NOT_ACCEPTED',
  ERR_ACCEPT_TOS_REQUIRED: 'ERR_ACCEPT_TOS_REQUIRED',
  ERR_CONFIRMATION_CODE_REQUIRED: 'ERR_CONFIRMATION_CODE_REQUIRED',
  ERR_INVALID_JLPT_LEVEL: 'ERR_INVALID_JLPT_LEVEL',
  ERR_JLPT_LEVEL_REQUIRED: 'ERR_JLPT_LEVEL_REQUIRED',
  ERR_INVALID_CATEGORY: 'ERR_INVALID_CATEGORY',
  ERR_CATEGORY_REQUIRED: 'ERR_CATEGORY_REQUIRED',
  ERR_LANGUAGE_REQUIRED: 'ERR_LANGUAGE_REQUIRED',
  ERR_LANGUAGE_ID_NOT_VALID: 'ERR_LANGUAGE_ID_NOT_VALID'
};
