---

name: Deploy workflow

run-name: ${{ github.actor }} commit and deploy
on:
  push:
    branches:
      - main

jobs:
  test_and_lint_server:
    name: Test and lint server
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: postgres
      SERVER_SKIP_CI: 1
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: docker-compose --file ../docker-tests/docker-compose.yaml up --abort-on-container-exit --exit-code-from back-end-test
      - name: Run linter
        run: yarn run lint
      - name: Deploy backend to production branch
        if: success()
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: backend-production
          FOLDER: server
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_and_lint_client:
    name: Test and lint client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Run linter
        run: yarn run lint
      - name: Deploy frontend to production branch
        if: success()
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: frontend-production
          FOLDER: client
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint_yaml_files:
    name: Lint project YAML files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML files
        run: yamllint .
