name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - uses: actions/checkout@master
        with:
          node-version: '16'
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ','), '#skip') }}
      - name: npm install
        run: npm install
      - name: run integration tests
        id: test
        run: npm test
        env:
          TEST_POSTGRE_URL: ${{ secrets.TEST_POSTGRE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
      - name: push to production branch         # if tests pass and #deploy used
        if: ${{ steps.test.outcome == 'success' && contains(join(github.event.commits.*.message, ','), '#deploy') }}
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: production
          github_token: ${{ secrets.GITHUB_TOKEN }}
