name: Commit workflow

run-name: ${{ github.actor }} commit
on:
  push:
    branches:
      - main

jobs:
  test_and_lint_server:
    name: Test and lint server
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: postgres
      SERVER_SKIP_CI: 1
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: docker-compose --file ../docker-tests/docker-compose.yaml up --abort-on-container-exit --exit-code-from back-end-test
      - name: Run linter
        run: npm run lint
      - name: Copy client directory to frontend-production
        if: success()
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout frontend-production
          rm -rf client
          cp -r ../client client
          git add client
          git commit -m "Update client directory"
          git push origin frontend-production